# Generated by Django 5.0 on 2023-12-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_сountrymodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сountrymodels',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='cards',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.сountrymodels', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='сountrymodels',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Код страны'),
        ),
    ]
