# Generated by Django 5.0 on 2023-12-14 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_сountrymodels_options_cards_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='main.сountrymodels', verbose_name='Страна'),
        ),
    ]
