# Generated by Django 5.0 on 2023-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_cards_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='main_cards',
            field=models.BooleanField(default=False, verbose_name='Основная карточка'),
        ),
    ]
