# Generated by Django 5.0 on 2023-12-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cards_main_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сountrymodels',
            name='country_code',
            field=models.CharField(max_length=5, verbose_name='Код страны'),
        ),
    ]
