# Generated by Django 5.0 on 2023-12-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cards_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сountrymodels',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Код страны'),
        ),
    ]
