# Generated by Django 5.0 on 2023-12-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_сountrymodels_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сountrymodels',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
    ]
