# Generated by Django 5.0 on 2023-12-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_сountrymodels_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='main_cards',
        ),
    ]
